blogger_blog_homepage:
    path: /{page}
    defaults:
      page: 1
      _controller: BloggerBlogBundle:Article:index

blogger_blog_page:
    path: /page
    defaults:
      page: 1
      _controller: BloggerBlogBundle:Article:index

blogger_blog_about:
    path: /page/about
    defaults: { _controller: BloggerBlogBundle:Page:about }

blogger_blog_contact:
    path:  /page/contact
    defaults: { _controller: BloggerBlogBundle:Page:contact }

blogger_blog_show:
    path:  /page/article/{slug}
    defaults: { _controller: BloggerBlogBundle:Article:show }

blogger_blog_comment_create:
    path:  /comment/{articleId}
    defaults: { _controller: BloggerBlogBundle:Comment:create }
    requirements:
        articleId: \d+

