# src/Blogger/BlogBundle/Resources/config/routing.yml
blogger_blog_homepage:
    path: /
    defaults: { _controller: BloggerBlogBundle:Default:index }

blogger_blog_page:
    path: /page
    defaults: { _controller: BloggerBlogBundle:Page:index }

blogger_blog_about:
    path: /page/about
    defaults: { _controller: BloggerBlogBundle:Page:about }

BloggerBlogBundle_contact:
    path:  /page/contact
    defaults: { _controller: BloggerBlogBundle:Page:contact }