services:
#    blogger_blog.example:
#        class: Blogger\BlogBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]


    form.type.enquire_type:
        class: Blogger\BlogBundle\Form\EnquiryType
        tags: [form.choice_list_factor]

    blogger_blog.fixtures.article:
        class: Blogger\BlogBundle\DataFixtures\ORM\ArticleFixtures
        tags: [doctrine.fixture.orm]

    blogger_blog.fixtures.comment:
        class: Blogger\BlogBundle\DataFixtures\ORM\CommentFixtures
        tags: [doctrine.fixture.orm]

    blogger_blog.twig.extension:
        class: Blogger\BlogBundle\Twig\Extensions\BloggerBlogExtension
        tags: [twig.extension]

    pagerfanta.view.default:
        class: Pagerfanta\View\DefaultView
        public: false
        tags: [{ name: pagerfanta.view, alias: default }]

    phpro.captcha-service:
        class: Blogger\BlogBundle\Utils\Recaptcha
        arguments: ["%recaptcha_secretkey%"]


    custom.event.contact_page:
        class: Blogger\BlogBundle\EventSubscriber\ContactPageEventSubscriber
        tags:
            - { name: kernel.event_listener, event: custom.event.contact_page, method: onCustomEvent }
        arguments: ['@phpro.mailer.mailer_service']

    phpro.mailer.mailer_service:
        class: Blogger\BlogBundle\Mailer\MailerService
        arguments:
            - '@twig'
            - '@swiftmailer.mailer'
        calls:
            - method: setLogger
              arguments:
                  - '@logger'

    phpro.extractor.tag_extractor:
        class: Blogger\BlogBundle\Extractor\TagExtractor